name: "Update site"
description: "Runs the dryrock module and pushes any changes to the repository."

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --deploy

    - name: Update
      shell: bash
      run: |
        pipenv run python -m dryrock

    - name: Set current date and time as env variable
      shell: bash
      run: echo "::set-env name=NOW::$(date +'%Y-%m-%d %H:%M')"

    - name: Configure Git
      shell: bash
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "github-actions"

    - name: Commit and push changes
      shell: bash
      run: |
        git diff --quiet --exit-code || git commit -a -m "AUTO COMMIT: Update at $NOW"
        git push
