name: Deploy site

on:
  push:
    branches: main

jobs:
  deploy-site:

    runs-on: windows-latest

    steps:
    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: 'gh-pages'
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config --local core.autocrlf true
        git config --local user.email "github-actions@github.com"
        git config --local user.name "github-actions"

    - name: Merge changes from main branch
      run: |
        git merge --commit --no-ff origin/main
        git push
