name: Deploy site

on:
  push:
    branches: main

jobs:
  deploy-site:

    runs-on: windows-latest

    steps:
    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: 'gh-pages'

    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --deploy

    - name: Merge changes from main branch
      run: git merge --commit --no-ff main

    - name: Update
      run: pipenv run python -m dryrock

    - name: Set current date and time as env variable
      # run: echo "::set-env name=NOW::$(date +'%Y-%m-%d %H:%M:%S')"
      run: $Env:NOW = Get-Date -Format "yyyy-MM-dd HH:mm"

    - name: Commit and push changes
      run: git config --local core.autocrlf true
      run: git config --local user.email "no-email@auto.com"
      run: git config --local user.name "Auto Updater"
      run: git diff --quiet && git commit -a -m "AUTO COMMIT: Merging main at $Env:NOW"
      run: git push
