
name: CD

on: push
  # release:
  #   types: [published]

jobs:
  deploy_release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: 'gh-pages'

      - name: Merge and push
        run: |
          git config user.email "no-email@auto.com"
          git config user.name "Auto Updater"
          git pull origin ${{ github.ref }} --no-edit --rebase
          git push

  update-site:
    needs: [deploy_release]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: 'gh-pages'

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update
        run: |
          python -m dryrock

      - name: Set current date as env variable
        run: echo "::set-env name=NOW::$(date +'%Y-%m-%d %H:%M:%S')"

      - name: Commit and push changes
        run: |
          git config user.email "no-email@auto.com"
          git config user.name "Auto Updater"
          git diff --quiet || git commit -a -m "AUTO COMMIT: Update at $NOW"
          git push
