# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint and test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build_and_test:
    runs-on: windows-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev --python 3.8

    - name: Lint with flake8
      run: pipenv run flake8

    - name: Lint with mypy
      run: pipenv run mypy

    - name: Test with pytest
      run: pipenv run pytest
