name: Lint and test

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev --python 3.13

      - name: Lint with flake8
        run: pipenv run flake8

      - name: Test with pytest
        run: pipenv run pytest
