
name: Python application

on: push
  #schedule:
  #  - cron: '0 7,10,13,15,18,21 * * *'

jobs:
  update:

    env:
      EMAIL: ${{ secrets.EMAIL }}

    runs-on: ubuntu-latest

    steps:
    - name: Integrate source code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Update
      run: |
        python -m dryrock

    - name: Set current date as env variable
      run: echo "::set-env name=NOW::$(date +'%Y-%m-%dT%H:%M:%S')"

    - name: Commit
      run: |
        git commit --author='Auto Updater <no-email@auto.com>' -a -m 'AUTO COMMIT: Update at $NOW'

    - name: Push
      run: |
        git push
