
name: Python application

on: push
  #schedule:
  #  - cron: '0 7,10,13,15,18,21 * * *'

jobs:
  update:

    env:
      EMAIL: ${{ secrets.EMAIL }}

    runs-on: ubuntu-latest

    steps:
    - name: Integrate source code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Update
      run: |
        python -m dryrock

    - name: Commit
      run: |
        git --author=${EMAIL} -a

    - name: Push
      run: |
        git push
