
name: Python application

on:
  schedule:
    - cron: '0 7,10,13,15,18,21 * * *'

jobs:
  update:

    runs-on: ubuntu-latest

    steps:
    - name: Integrate source code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Update
      run: |
        python -m dryrock

    - name: Commit
      run: |
        git add -A && git commit

    - name: Push
      run: |
        git push
