name: Update site

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

on:
  schedule:
    - cron: "13,43 * * * *" # Run at 13 and 43 minutes past the hour every hour

jobs:
  update-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: "gh-pages"

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Update site
        uses: ./.github/actions/update-site
