
name: Update site

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

on:
  schedule:
    - cron: '13,43 5-23 * * *'

jobs:
  update-site:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: 'gh-pages'

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Update site
      uses: ./.github/actions/update-site
