
name: Update site

on:
  schedule:
    - cron: '13,43 5-23 * * *'

jobs:
  update-site:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: 'gh-pages'

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --deploy

    - name: Update
      run: |
        pipenv run python -m dryrock

    - name: Set current date and time as env variable
      run: echo "::set-env name=NOW::$(date +'%Y-%m-%d %H:%M')"

    - name: Configure Git
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "github-actions"

    - name: Commit and push changes
      run: |
        git diff --quiet --exit-code || git commit -a -m "AUTO COMMIT: Update at $NOW"
        git push
